##

<div class="emphasized verticalcenterdiv">
a. Naming files and directories
b. Structuring projects and related coding conventions
c. Coding style
</div>

<div class="footer"> Scientific computing basics </div>


##

**File and directory naming**

- Assume case-sensitivity
- Spaces = bad
- Use camelCase, PascalCase, or delimiter\_separated
- Use numbering for files executed sequentially
- 0-padding for numbered names to retain sorting (e.g. 01, 02,... 10)
- Use the standard (ISO 8601) format for dates: YYYY-MM-DD or YYYYMMDD
- Use descriptive names and only obvious abbreviations

<div class="footer"> Scientific computing basics </div>


##

**File and directory naming**

Good project directory name:

```
    StatinDiscontinuationStudy
```

Good filenames:

```
    01_clean_data.R
    02_descriptives.R
    03_analysis_aim1_hypothesis1.R
    04_analysis_aim1_hypothesis2.R
    05_analysis_aim2_hypothesis1.R
```
<div class="footer"> Scientific computing basics  </div>


##

**Project structure**

- New users should be able to quickly recognize and comprehend the structure.
- Include a README file to explain structure, what files do, and how to execute them.
- Use a build script, makefile, or *designate a master file*

- Set working directory once and otherwise use *relative file paths* 

```{r, eval=FALSE, echo=T}
# Setting working directory
setwd("C:/Users/myusername/Projects/thisprojectdirectory")
# and using relative filepaths
mydata <- read.csv("./data/my_raw_data_file.csv")
source("./R/01_clean_data.R")
```

<div class="footer"> Scientific computing basics </div>


<!--
##

**Project structure**

<div class="codefont">
```{bash, echo=FALSE}
cd ~/Projects/BERD/berd006_rr_workshops/
tree -L 2 reproducible_reporting/
```
</div>

-->

##

**Project structure**

```
MyProject/
    |— data/
          |— rawdata/
    |— documents/
    |— libraries/
    |— output/
          |— figures/
          |— tables/
          |- myreport.docx
    |— R/
    |- Rmd/
          |- myreport.Rmd
    |— sas/
    |— build.R
    |— README.txt
```

<div class="footer"> Scientific computing basics </div>


##

**Code style**

- All code files should be executable, and sequentially so.
- Minimize extraneous operations, or move to an 'appendix' script.
- Limit line length (80 or 100 characters)
- Limit file length to "something reasonable" (~ 100 lines)

<div class="footer"> Scientific computing basics </div>


##

**Code style**

- Use comments to explain 'why', good code to explain 'what'.
- Use headers at top of file and to denote major sections.
- Human readable first, optimization second.
- Consistent indenting, capitalization, and spacing.
    - Use spaces around operators =+-/\*&%\$ and after commas.
- Consistency is key!
- Use a [style](https://google.github.io/styleguide/Rguide.xml)
  [guide](http://adv-r.had.co.nz/Style.html)

<div class="footer"> Scientific computing basics </div>



